{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8sdemo.serviceAccountName" . }}
  labels:
{{ include "k8sdemo.labels" . | indent 4 }}
{{- end -}}
